//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendord.Desktop.WPF.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vendord.Desktop.WPF.App.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Products.
        /// </summary>
        internal static string AllOrderProductsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllOrderProductsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string AllOrdersViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllOrdersViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string AllProductsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllProductsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Products.
        /// </summary>
        internal static string MainWindowViewModel_Command_OrderProducts {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_OrderProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string MainWindowViewModel_Command_Orders {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string MainWindowViewModel_Command_Products {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        internal static string MainWindowViewModel_Command_Sync {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Grocer Salt Spring.
        /// </summary>
        internal static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        internal static string SyncCommandsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("SyncCommandsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Products.
        /// </summary>
        internal static string SyncCommandsViewModel_ImportXmlProducts {
            get {
                return ResourceManager.GetString("SyncCommandsViewModel_ImportXmlProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Vendors.
        /// </summary>
        internal static string SyncCommandsViewModel_ImportXmlVendors {
            get {
                return ResourceManager.GetString("SyncCommandsViewModel_ImportXmlVendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Orders.
        /// </summary>
        internal static string SyncCommandsViewModel_SyncDbOrders {
            get {
                return ResourceManager.GetString("SyncCommandsViewModel_SyncDbOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Products, Vendors, and Departments.
        /// </summary>
        internal static string SyncCommandsViewModel_SyncDbProductsVendorsDepartments {
            get {
                return ResourceManager.GetString("SyncCommandsViewModel_SyncDbProductsVendorsDepartments", resourceCulture);
            }
        }
    }
}
